app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager

class User(UserMixin, db.Model):
    """
    Create a user table with email, username, firstname, lastname, password
    """

    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    first_name = db.Column(db.String(60), index=True)
    last_name = db.Column(db.String(60), index=True)
    password_hash = db.Column(db.String(128))
    is_admin = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        """
        Prevent password from being accessed
        """

        raise AttributeError('password is not a readable attribute')
    
    @password.setter
    def password(self, password):
        """
        Set hashed password
        """

        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed passwords match actual password
        """
        
        return check_password_hash(self.password_hash, password)
    
    def __repr__(self):
        return '<User: {}>'.format(self.username)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    """
    Form for users to search in a string text box with a submit field.
    """
    
    search = StringField('', validators=[DataRequired()])
    submit = SubmitField('Search')

app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap

from config import app_config

db = SQLAlchemy()
login_manager = LoginManager()

def create_app(config_name):
    """
    Creates the flask application, registers it with Bootstrap, initializes it and sets up flask blueprints.
    Also initializes database tables.
    """
    
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.secret_key = 'a super secret key'
    
    Bootstrap(app)
    with app.app_context():
        db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"

    from app import models
    with app.app_context():
        db.create_all()
    
    migrate = Migrate(app, db)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    return app

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import (
    redirect,
    render_template,
    url_for
)
from flask_login import login_required
from flask_paginate import Pagination, get_page_args
from . import home
from forms import SearchForm
from ..search import searching_elastic, searching_mongo

@home.route('/')
def homepage():
    """
    Render the homepage template on / route
    """

    return render_template('home/index.html', title="Welcome")

@home.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    """
    Render the dashboard template on /search route after logging in
    """

    search_form = SearchForm()
    if search_form.validate_on_submit():
        return redirect((url_for('home.search_results', query=search_form.search.data)))
    return render_template('home/search.html', form=search_form ,title="Search")

@home.route('/search_results/<query>/')
@login_required
def search_results(query):
    """
    Render the search results template on /search_results/<query> and chooses how many results
    to display per page using Pagination
    """

    page, per_page, offset = get_page_args()
    search_result = searching_elastic.searching_elastic(query)
    # array that will only display a couple of results per page depending on the offset
    page_result = search_result[offset:per_page*page]
    pagination = Pagination(page=page, per_page=per_page, offset=offset,
                            total=len(search_result), record_name='page_result', css_framework='foundation')
    return render_template('home/search_results.html', results=page_result, pagination=pagination, per_page=per_page)

@home.route('/search_results/<query>/<mongo_id>')
@login_required
def mongo_results(query, mongo_id):
    """
    After clicking on a page in the search results template, render mongo results template
    to show the data from the mongodb that matches the id returned from elastic.
    """
    
    result = searching_mongo.searching_mongo(mongo_id)
    return render_template('home/mongo_results.html', results=result)

app/search/__init__.py
# initializing module

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ title }} | Search Me</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" r
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
            <div class="container topnav">
                <div class="navbar-header">
                    {% if current_user.is_authenticated %}
                    <a class="navbar-brand topnav" href="{{ url_for('home.search') }}">Search Me</a>
                    {% else %}
                    <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Search Me</a>
                    {% endif %}
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated %}
                        <li>
                            <a href="{{ url_for('home.search') }}">Search</a>
                        </li>
                        <li>
                            <a href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                        <li>
                            <a>
                                <i class="fa fa-user"></i> Hello, {{ current_user.first_name }} {{ current_user.last_name }}!</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{{ url_for('home.homepage') }}">Home</a>
                        </li>
                        <li>
                            <a href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        <li>
                            <a href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="wrapper">
            {% block body %} {% endblock %}
            <div class="push"></div>
        </div>
    </body>
</html>

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Search Me{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Search Me</h1>
                    <hr class="intro-divider">
                    <h3>Before you can search, please Register or Login</h3>
                    <a class="btn btn-default" href="{{ url_for('auth.register') }}" role="button">Register</a>
                    <a class="btn btn-default" href="{{ url_for('auth.login') }}" role="button">Login</a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/mongo_results.html
{% extends "base.html" %}
{% block title %}Mongo Results{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h3>Mongo Results</h3>
                    <hr class="intro-divider">
                    <h2>{{ results["sample_data"].name }}</h2>
                    <h3>{{ results["sample_data"].date }}</h3>
                    <p>{{ results["sample_data"].description }}</p>
                    <br />
                    <p>To learn more:</p>
                    <p>{{ results["sample_data"].url }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/search.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Search{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Search</h1>
                    <hr class="intro-divider">
                    <h4>Currently you can only search for holidays (eg. Christmas or New Year's Eve)</h4>
                     {{ wtf.quick_form(form) }}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/search_results.html
{% extends "base.html" %}
{% block title %}Search Results{% endblock %}
{% block body%}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h3>Search Results</h3>
                    <hr class="intro-divider">
                    {% for result in results %}
                        <p><a href="/search_results/{{result._source.data}}/{{result._id}}" target="_blank">{{ result._source.data }} {{ result._source.date}}</a></p>
                    {% endfor %}
                    {{ pagination.info }}
                    {{ pagination.links }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}